### ISSUE TITLE
Seeding Files

### ISSUE THREAD

**Issue by werewolfe** [nuzzesick/storm-desktop#33]
It doesn't look like there is a feature to seed files uploaded by the user. It looks like it was started, but not implemented in /api/controlers/torrent.js, "createTorrent". Are there plans to implement this?

**Comment by nuzzesick** [comment]
Hey Adam! I'm not working on Storm at this moment because of time. Create torrents was the next feature I always wanted to implement. 
Storm is an open source project, I would really appreciate if you want to contribute and build the feature.

Did you like Storm? What other ideas do you have?

**Comment by werewolfe** [comment]
Thanks Matias. I’ve started adding the feature. If I can implement it well, I’ll make a PR.

Best,
Adam

Sent from my iPhone

On Sep 20, 2022, at 3:33 PM, Matías ***@***.***> wrote:

﻿

Hey Adam! I'm not working on Storm at this moment because of time. Create torrents was the next feature I always wanted to implement.
Storm is an open source project, I would really appreciate if you want to contribute and build the feature.

Did you like Storm? What other ideas do you have?

**Comment by nuzzesick** [comment]
Nice, thanks!
